### ISSUE TITLE
Meer gebruik van h2-6 tags voor hiërarchie

### ISSUE THREAD

**Issue by Seijno** [zoepje/the-startup-responsive-interactieve-website#11]
`<section class="solutions-nav-menu">`
De code heeft te weinig h2-6 tags hierdoor is er weinig hiërarchie binnen je code. Je zou het kunnen toevoegen of als het niet past bij je pagina, gebruik dan divs om duidelijk te maken wat iets is door middel van class. Maar liever niet in de sections.

oplossing: [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing)

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/a8b72933a59c02ddb94e3f249e958eed4f7ed6e7/index.html#L51-L94

https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/a8b72933a59c02ddb94e3f249e958eed4f7ed6e7/index.html#L195

https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/a8b72933a59c02ddb94e3f249e958eed4f7ed6e7/index.html#L293

Ik heb dit gefixt.
