### ISSUE TITLE
geen spaties bij hrefs

### ISSUE THREAD

**Issue by Seijno** [zoepje/the-startup-responsive-interactieve-website#12]
`<a class="call-us" href="tel: 0208461905">`
Op dit moment komen er errors omdat je een spatie in de href gebruikt. haal dit weg en je hebt het gefixt!

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/aded6a4da2565a56c2f31640e6690ef62b54f197/index.html#L22

Is gefixt
