### ISSUE TITLE
h1 structuur veranderen

### ISSUE THREAD

**Issue by Seijno** [zoepje/the-startup-responsive-interactieve-website#13]
Op dit moment heb jij de catch-phrase als een h1, dit is incorrect aangezien het niet op de top van je pagina staat.

Ik zou het naar een h2 veranderen en met styling dezelfde look geven. Ook zou ik de h1 dan naar boven gooien zodat het beter is voor bijv. screenreaders.

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/d5c05d165d3a8703652d5ee9af58bb8f074a7632/index.html#L176-L180

Dit heb ik verandert.
