### ISSUE TITLE
Link naar telefoonnnummer is niet juist

### ISSUE THREAD

**Issue by Khdulkadir** [zoepje/the-startup-responsive-interactieve-website#14]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/2d7c20ba168783d80660a77f09355ef7f25f6431/index.html#L22

Er zit een spatie in je tel: link die er niet hoort te zijn.

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/aded6a4da2565a56c2f31640e6690ef62b54f197/index.html#L22

Is gefixt.
