### ISSUE TITLE
Bestaandsnaam van img heeft een spatie

### ISSUE THREAD

**Issue by Khdulkadir** [zoepje/the-startup-responsive-interactieve-website#15]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/2d7c20ba168783d80660a77f09355ef7f25f6431/index.html#L265

Bestaandsnaam van img heeft een spatie. Spaties zijn eigenlijk niet toegestaan bij bestandsnamen.

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/aded6a4da2565a56c2f31640e6690ef62b54f197/index.html#L265

Is gefixt.
