### ISSUE TITLE
HTML formatting

### ISSUE THREAD

**Issue by Jaywesterlow** [zoepje/the-startup-responsive-interactieve-website#19]
Line 22, 284, 404: spaties binnen a tag href niet toegestaan (href="tel: 0208461905").

Line 285: spaties binnen a tag href niet toegestaan (href="mailto: martijn@lifely.nl").

Line 265, 271: spaties in map naam niet toegestaan zorgt voor errors in de href (Assets/Foto_s/Case studies).

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/aded6a4da2565a56c2f31640e6690ef62b54f197/index.html#L22

https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/aded6a4da2565a56c2f31640e6690ef62b54f197/index.html#L285

https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/aded6a4da2565a56c2f31640e6690ef62b54f197/index.html#L265
Is gefixt.
