### ISSUE TITLE
De javascript ''const'' kun je sneller noteren.

### ISSUE THREAD

**Issue by TygoWolven** [zoepje/the-startup-responsive-interactieve-website#21]
In de javascript zie ik dat je gebruik maakt van de ''const''. Dat is een heel positief punt, hier heb ik alleen wel iets op aan te merken. Jij schrijft de ''const'' vrij uitgebreid op, maar dit kan ook op een snellere manier met minder characters.

https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/2d7c20ba168783d80660a77f09355ef7f25f6431/scripts/script.js#L1-L3

Hier onder zie je wat ik bedoel met het sneller noteren van de ''const''. Na elke regel moet je een komma schrijven, en bij de laatste regel pas de puntkomma. Door dit te doen hoef je maar 1 keer ''const'' op te schrijven, in plaats van dat je het 3 keer doet.

![image](https://github.com/zoepje/the-startup-responsive-interactieve-website/assets/144010858/adb878a6-e346-421a-ace5-8ceffe622458)

**Comment by zoepje** [comment]
https://github.com/zoepje/the-startup-responsive-interactieve-website/blob/3cc97ab8bca644af690dbe3a686c4bc6c0b4439f/scripts/script.js#L1-L3

Tanks ik heb het verandert.
